### ISSUE TITLE
Sample Code for Asyncio doesn't work with the latest Couchbase library

### ISSUE THREAD

**Issue by peidaqi** [couchbase/docs-sdk-python#212] opened 2022-09-26 21:46 UTC
To be specific, the latest Couchbase library (4.0.4) breaks:
txcouchbase_operations.py

And the first two lines:
from twisted.internet import reactor
from txcouchbase.cluster import TxCluster

throws an error:
ReactorAlreadyInstalledError: reactor already installed

I'm using twisted 22.8.0 and Python 3.8.13. After downgrading couchbase python lib to 3.1.2, everything works.

This bug basically makes the txcouchbase lib useless. Please fix it asap. Thanks.

**Comment by thejcfactor** [comment] 2022-09-27 16:38
Hi @peidaqi - I have created a ticket to address updating the async examples in our JIRA project:  [DOC-10467](https://issues.couchbase.com/browse/DOC-10467).  In the interim, please see the examples we provide in the 4.x SDK repo:  [txcouchbase examples](https://github.com/couchbase/couchbase-python-client/tree/master/examples/txcouchbase).

Also, I updated [PYCBC-1412](https://issues.couchbase.com/browse/PYCBC-1412) with more information as there is not a bug, it is a change that is needed when moving to the 4.x SDK.  All you should need to do (since you have a a Twisted version > 21.7.0) is `import txcouchbase` prior to importing the reactor.

**Closed as completed** 2022-10-03 08:58 UTC
